// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/auth/api-keys": {
            "post": {
                "security": [
                    {
                        "InternalKey": []
                    }
                ],
                "description": "Create a new API key for a consumer or provider",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Create a new API key",
                "parameters": [
                    {
                        "description": "API key creation request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.CreateAPIKeyRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/auth.CreateAPIKeyResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_sentnl_inferoute-node_pkg_common.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_sentnl_inferoute-node_pkg_common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_sentnl_inferoute-node_pkg_common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/auth/entities": {
            "post": {
                "security": [
                    {
                        "InternalKey": []
                    }
                ],
                "description": "Create a new consumer or provider for an existing user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Create a new consumer or provider",
                "parameters": [
                    {
                        "description": "Entity creation request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.CreateEntityRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/auth.CreateEntityResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_sentnl_inferoute-node_pkg_common.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_sentnl_inferoute-node_pkg_common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_sentnl_inferoute-node_pkg_common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/auth/hold": {
            "post": {
                "description": "Place a hold on a user's balance for a pending transaction",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Place a hold on a user's balance",
                "parameters": [
                    {
                        "description": "Hold deposit request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.HoldDepositRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.HoldDepositResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_sentnl_inferoute-node_pkg_common.ErrorResponse"
                        }
                    },
                    "402": {
                        "description": "Payment Required",
                        "schema": {
                            "$ref": "#/definitions/github_com_sentnl_inferoute-node_pkg_common.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_sentnl_inferoute-node_pkg_common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_sentnl_inferoute-node_pkg_common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/auth/release": {
            "post": {
                "description": "Release a hold on a user's balance and return the funds to available",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Release a hold on a user's balance",
                "parameters": [
                    {
                        "description": "Release hold request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.ReleaseHoldRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.ReleaseHoldResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_sentnl_inferoute-node_pkg_common.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_sentnl_inferoute-node_pkg_common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_sentnl_inferoute-node_pkg_common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/auth/users": {
            "post": {
                "description": "Create a new user with a username, API key and initial balance",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Create a new user",
                "parameters": [
                    {
                        "description": "User creation request with username and initial balance",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.CreateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/auth.CreateUserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_sentnl_inferoute-node_pkg_common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_sentnl_inferoute-node_pkg_common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/auth/validate": {
            "post": {
                "description": "Validate an API key and return user information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Validate an API key",
                "parameters": [
                    {
                        "description": "API key validation request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.ValidateAPIKeyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.ValidateAPIKeyResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_sentnl_inferoute-node_pkg_common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_sentnl_inferoute-node_pkg_common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/cloudflare/tunnel/refresh-token": {
            "post": {
                "security": [
                    {
                        "InternalKey": []
                    }
                ],
                "description": "Allows a provider client to get a new/current token for their tunnel.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cloudflare"
                ],
                "summary": "Refresh or retrieve the token for an existing Cloudflare tunnel",
                "parameters": [
                    {
                        "description": "Refresh token request including API key and refresh flag",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/cloudflare.RefreshTokenRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/cloudflare.RefreshTokenResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "$ref": "#/definitions/github_com_sentnl_inferoute-node_pkg_common.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - API key invalid or not a provider",
                        "schema": {
                            "$ref": "#/definitions/github_com_sentnl_inferoute-node_pkg_common.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found - Tunnel does not exist for this provider",
                        "schema": {
                            "$ref": "#/definitions/github_com_sentnl_inferoute-node_pkg_common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_sentnl_inferoute-node_pkg_common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/cloudflare/tunnel/request": {
            "post": {
                "security": [
                    {
                        "InternalKey": []
                    }
                ],
                "description": "Authenticates provider via API key, then creates/updates a Cloudflare tunnel and DNS, returning token and hostname.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cloudflare"
                ],
                "summary": "Request or get details of a Cloudflare tunnel for a provider",
                "parameters": [
                    {
                        "description": "Tunnel request details including API key and service URL",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/cloudflare.RequestTunnelRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/cloudflare.RequestTunnelResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "$ref": "#/definitions/github_com_sentnl_inferoute-node_pkg_common.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - API key invalid or not a provider",
                        "schema": {
                            "$ref": "#/definitions/github_com_sentnl_inferoute-node_pkg_common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_sentnl_inferoute-node_pkg_common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/health/provider/{provider_id}": {
            "get": {
                "description": "Get detailed health status for a specific provider",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Get provider health status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Provider ID",
                        "name": "provider_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/health.ProviderHealthResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_sentnl_inferoute-node_pkg_common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_sentnl_inferoute-node_pkg_common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/health/providers/check-stale": {
            "post": {
                "description": "Checks and updates providers that haven't sent a health check recently",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Manually trigger stale provider checks",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/health.TriggerHealthChecksResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_sentnl_inferoute-node_pkg_common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/health/providers/filter": {
            "get": {
                "description": "Get a list of healthy providers offering a specific model within cost constraints. If no model is specified, returns the cheapest available model for each provider.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "providers"
                ],
                "summary": "Filter providers by model, tier, health status, and cost",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Optional name of the model to filter by. If not provided, returns cheapest model per provider",
                        "name": "model_name",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Optional tier to filter by",
                        "name": "tier",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "Maximum cost per token (applies to both input and output)",
                        "name": "max_cost",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/health.FilterProvidersResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_sentnl_inferoute-node_pkg_common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_sentnl_inferoute-node_pkg_common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/health/providers/healthy": {
            "get": {
                "description": "Get a list of all providers with green health status",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Get all healthy nodes",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/health.HealthyNodeResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_sentnl_inferoute-node_pkg_common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/health/providers/update-tiers": {
            "post": {
                "description": "Updates provider tiers based on their health history",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Manually trigger provider tier updates",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/health.TriggerHealthChecksResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_sentnl_inferoute-node_pkg_common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/health/providers/user": {
            "get": {
                "description": "Get a list of providers belonging to a specific user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "providers"
                ],
                "summary": "Filter providers by user ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID to filter by",
                        "name": "user_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Optional model name to filter by",
                        "name": "model_name",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/health.FilterProvidersResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_sentnl_inferoute-node_pkg_common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_sentnl_inferoute-node_pkg_common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/provider/api_url": {
            "put": {
                "description": "Update the API URL for the authenticated provider",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Provider"
                ],
                "summary": "Update provider API URL",
                "parameters": [
                    {
                        "description": "API URL update",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/provider.UpdateAPIURLRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/provider.UpdateAPIURLResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_sentnl_inferoute-node_pkg_common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/provider/health": {
            "get": {
                "description": "Get the current health status of the authenticated provider",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Provider"
                ],
                "summary": "Get provider health status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/provider.GetProviderHealthResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_sentnl_inferoute-node_pkg_common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_sentnl_inferoute-node_pkg_common.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Push provider's current health and model status",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Provider"
                ],
                "summary": "Push provider health data",
                "parameters": [
                    {
                        "description": "Health data",
                        "name": "health",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/provider.ProviderHealthPushRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_sentnl_inferoute-node_pkg_common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/provider/models": {
            "get": {
                "description": "Get all models configured for the authenticated provider",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Provider"
                ],
                "summary": "List provider's models",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/provider.ListModelsResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Add a new model configuration for the authenticated provider",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Provider"
                ],
                "summary": "Add a new model for the provider",
                "parameters": [
                    {
                        "description": "Model configuration",
                        "name": "model",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/provider.AddModelRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/provider.ProviderModel"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_sentnl_inferoute-node_pkg_common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/provider/models/{model_id}": {
            "put": {
                "description": "Update an existing model configuration",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Provider"
                ],
                "summary": "Update a model",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Model ID",
                        "name": "model_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated model configuration",
                        "name": "model",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/provider.UpdateModelRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/provider.ProviderModel"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_sentnl_inferoute-node_pkg_common.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_sentnl_inferoute-node_pkg_common.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete an existing model configuration",
                "tags": [
                    "Provider"
                ],
                "summary": "Delete a model",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Model ID",
                        "name": "model_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_sentnl_inferoute-node_pkg_common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/provider/pause": {
            "put": {
                "description": "Update the pause status of the authenticated provider",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Provider"
                ],
                "summary": "Update provider pause status",
                "parameters": [
                    {
                        "description": "Pause status update",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/provider.UpdatePauseRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/provider.UpdatePauseResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_sentnl_inferoute-node_pkg_common.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_sentnl_inferoute-node_pkg_common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/provider/validate_hmac": {
            "post": {
                "description": "Validates an HMAC for a provider and returns the associated request data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Provider"
                ],
                "summary": "Validate HMAC",
                "parameters": [
                    {
                        "description": "HMAC to validate",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/provider.ValidateHMACRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/provider.ValidateHMACResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_sentnl_inferoute-node_pkg_common.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_sentnl_inferoute-node_pkg_common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_sentnl_inferoute-node_pkg_common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/send_requests": {
            "post": {
                "description": "Sends a request to a specific provider and waits for response",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Provider Communication"
                ],
                "summary": "Send request to provider",
                "parameters": [
                    {
                        "description": "Request details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/provider_comm.SendRequestRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Provider response",
                        "schema": {}
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_sentnl_inferoute-node_pkg_common.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_sentnl_inferoute-node_pkg_common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_sentnl_inferoute-node_pkg_common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/chat/completions": {
            "post": {
                "description": "Handles the complete request flow from consumer to provider",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "orchestrator"
                ],
                "summary": "Process an OpenAI-compatible API request",
                "parameters": [
                    {
                        "description": "OpenAI request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/pkg_api_orchestrator.OpenAIRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Provider response",
                        "schema": {}
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/github_com_sentnl_inferoute-node_pkg_common.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_sentnl_inferoute-node_pkg_common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_sentnl_inferoute-node_pkg_common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/models": {
            "get": {
                "description": "Get a list of available models in OpenAI-compatible format",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Models"
                ],
                "summary": "Get available models",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ai_applications.ModelResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_sentnl_inferoute-node_pkg_common.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "ai_applications.ModelDetail": {
            "type": "object",
            "properties": {
                "created": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "max_model_len": {
                    "type": "integer"
                },
                "object": {
                    "type": "string"
                },
                "owned_by": {
                    "type": "string"
                },
                "parent": {},
                "root": {
                    "type": "string"
                }
            }
        },
        "ai_applications.ModelResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ai_applications.ModelDetail"
                    }
                },
                "object": {
                    "type": "string"
                }
            }
        },
        "auth.Balance": {
            "type": "object",
            "properties": {
                "available_amount": {
                    "type": "number"
                },
                "created_at": {
                    "type": "string"
                },
                "held_amount": {
                    "type": "number"
                },
                "id": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "auth.Consumer": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "max_input_price_tokens": {
                    "type": "number"
                },
                "max_output_price_tokens": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "auth.CreateAPIKeyRequest": {
            "type": "object",
            "required": [
                "description",
                "type",
                "user_id"
            ],
            "properties": {
                "consumer_id": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "provider_id": {
                    "type": "string"
                },
                "type": {
                    "type": "string",
                    "enum": [
                        "consumer",
                        "provider"
                    ]
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "auth.CreateAPIKeyResponse": {
            "type": "object",
            "properties": {
                "api_key": {
                    "type": "string"
                },
                "consumer_id": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "provider_id": {
                    "type": "string"
                }
            }
        },
        "auth.CreateEntityRequest": {
            "type": "object",
            "required": [
                "name",
                "type",
                "user_id"
            ],
            "properties": {
                "api_url": {
                    "description": "Only for providers",
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string",
                    "enum": [
                        "consumer",
                        "provider"
                    ]
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "auth.CreateEntityResponse": {
            "type": "object",
            "properties": {
                "consumer": {
                    "$ref": "#/definitions/auth.Consumer"
                },
                "provider": {
                    "$ref": "#/definitions/auth.Provider"
                }
            }
        },
        "auth.CreateUserRequest": {
            "type": "object",
            "required": [
                "username"
            ],
            "properties": {
                "username": {
                    "type": "string"
                }
            }
        },
        "auth.CreateUserResponse": {
            "type": "object",
            "properties": {
                "user": {
                    "$ref": "#/definitions/auth.User"
                }
            }
        },
        "auth.HoldDepositRequest": {
            "type": "object",
            "required": [
                "amount",
                "user_id"
            ],
            "properties": {
                "amount": {
                    "type": "number",
                    "minimum": 0
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "auth.HoldDepositResponse": {
            "type": "object",
            "properties": {
                "balance": {
                    "$ref": "#/definitions/auth.Balance"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "auth.Provider": {
            "type": "object",
            "properties": {
                "api_url": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "health_status": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_available": {
                    "type": "boolean"
                },
                "last_health_check": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "paused": {
                    "type": "boolean"
                },
                "tier": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "auth.ReleaseHoldRequest": {
            "type": "object",
            "required": [
                "amount",
                "user_id"
            ],
            "properties": {
                "amount": {
                    "type": "number",
                    "minimum": 0
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "auth.ReleaseHoldResponse": {
            "type": "object",
            "properties": {
                "balance": {
                    "$ref": "#/definitions/auth.Balance"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "auth.User": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "auth.ValidateAPIKeyRequest": {
            "type": "object",
            "required": [
                "api_key"
            ],
            "properties": {
                "api_key": {
                    "type": "string"
                }
            }
        },
        "auth.ValidateAPIKeyResponse": {
            "type": "object",
            "properties": {
                "available_balance": {
                    "type": "number"
                },
                "consumer_id": {
                    "type": "string"
                },
                "held_balance": {
                    "type": "number"
                },
                "provider_id": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                },
                "user_type": {
                    "type": "string"
                },
                "valid": {
                    "type": "boolean"
                }
            }
        },
        "cloudflare.RefreshTokenRequest": {
            "type": "object",
            "properties": {
                "refresh": {
                    "description": "Kept for now, can be removed if truly unused.",
                    "type": "boolean"
                }
            }
        },
        "cloudflare.RefreshTokenResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        },
        "cloudflare.RequestTunnelRequest": {
            "type": "object",
            "required": [
                "service_url"
            ],
            "properties": {
                "service_url": {
                    "type": "string"
                }
            }
        },
        "cloudflare.RequestTunnelResponse": {
            "type": "object",
            "properties": {
                "hostname": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "github_com_sentnl_inferoute-node_pkg_common.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "health.FilterProvidersResponse": {
            "type": "object",
            "properties": {
                "api_url": {
                    "type": "string"
                },
                "average_tps": {
                    "type": "number"
                },
                "health_status": {
                    "type": "string"
                },
                "input_cost": {
                    "type": "number"
                },
                "model_name": {
                    "type": "string"
                },
                "output_cost": {
                    "type": "number"
                },
                "provider_id": {
                    "type": "string"
                },
                "tier": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "health.HealthyNodeResponse": {
            "type": "object",
            "properties": {
                "latency_ms": {
                    "type": "integer"
                },
                "provider_id": {
                    "type": "string"
                },
                "tier": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "health.ProviderHealthResponse": {
            "type": "object",
            "properties": {
                "health_status": {
                    "type": "string"
                },
                "is_available": {
                    "type": "boolean"
                },
                "last_health_check": {
                    "type": "string"
                },
                "latency_ms": {
                    "type": "integer"
                },
                "provider_id": {
                    "type": "string"
                },
                "tier": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "health.TriggerHealthChecksResponse": {
            "type": "object",
            "properties": {
                "providers_updated": {
                    "type": "integer"
                },
                "tiers_updated": {
                    "type": "integer"
                }
            }
        },
        "pkg_api_orchestrator.Message": {
            "type": "object",
            "required": [
                "content",
                "role"
            ],
            "properties": {
                "content": {
                    "description": "Can be string, array, or map"
                },
                "role": {
                    "type": "string",
                    "enum": [
                        "system",
                        "user",
                        "assistant"
                    ]
                }
            }
        },
        "pkg_api_orchestrator.OpenAIRequest": {
            "type": "object",
            "required": [
                "model"
            ],
            "properties": {
                "frequency_penalty": {
                    "type": "number"
                },
                "logit_bias": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "number",
                        "format": "float64"
                    }
                },
                "max_tokens": {
                    "type": "integer"
                },
                "messages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/pkg_api_orchestrator.Message"
                    }
                },
                "model": {
                    "type": "string"
                },
                "n": {
                    "type": "integer"
                },
                "presence_penalty": {
                    "type": "number"
                },
                "prompt": {
                    "type": "string"
                },
                "sort": {
                    "type": "string",
                    "enum": [
                        "cost",
                        "throughput"
                    ]
                },
                "stop": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "stream": {
                    "type": "boolean"
                },
                "temperature": {
                    "type": "number"
                },
                "top_p": {
                    "type": "number"
                },
                "user": {
                    "type": "string"
                }
            }
        },
        "provider.AddModelRequest": {
            "type": "object",
            "required": [
                "input_price_tokens",
                "model_name",
                "output_price_tokens",
                "service_type"
            ],
            "properties": {
                "input_price_tokens": {
                    "type": "number",
                    "minimum": 0
                },
                "model_name": {
                    "type": "string"
                },
                "output_price_tokens": {
                    "type": "number",
                    "minimum": 0
                },
                "service_type": {
                    "enum": [
                        "ollama",
                        "exolabs",
                        "llama_cpp",
                        "vllm"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/provider.ServiceType"
                        }
                    ]
                }
            }
        },
        "provider.CloudflareInfo": {
            "type": "object",
            "properties": {
                "url": {
                    "type": "string"
                }
            }
        },
        "provider.GPUInfo": {
            "type": "object",
            "properties": {
                "cuda_version": {
                    "type": "string"
                },
                "driver_version": {
                    "type": "string"
                },
                "gpu_count": {
                    "type": "integer"
                },
                "is_busy": {
                    "type": "boolean"
                },
                "memory_free": {
                    "type": "integer"
                },
                "memory_total": {
                    "type": "integer"
                },
                "memory_used": {
                    "type": "integer"
                },
                "product_name": {
                    "type": "string"
                },
                "utilization": {
                    "type": "integer"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "provider.GetProviderHealthResponse": {
            "type": "object",
            "properties": {
                "health_status": {
                    "type": "string"
                },
                "is_available": {
                    "type": "boolean"
                },
                "last_health_check": {
                    "type": "string"
                },
                "latency_ms": {
                    "type": "integer"
                },
                "paused": {
                    "type": "boolean"
                },
                "provider_id": {
                    "type": "string"
                },
                "provider_type": {
                    "type": "string"
                },
                "tier": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "provider.ListModelsResponse": {
            "type": "object",
            "properties": {
                "models": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/provider.ProviderModel"
                    }
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "provider.ProviderHealthPushModel": {
            "type": "object",
            "properties": {
                "created": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "object": {
                    "type": "string"
                },
                "owned_by": {
                    "type": "string"
                }
            }
        },
        "provider.ProviderHealthPushRequest": {
            "type": "object",
            "required": [
                "data",
                "object"
            ],
            "properties": {
                "cloudflare": {
                    "$ref": "#/definitions/provider.CloudflareInfo"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/provider.ProviderHealthPushModel"
                    }
                },
                "gpu": {
                    "$ref": "#/definitions/provider.GPUInfo"
                },
                "object": {
                    "type": "string"
                },
                "provider_type": {
                    "type": "string"
                }
            }
        },
        "provider.ProviderModel": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "input_price_tokens": {
                    "type": "number"
                },
                "is_active": {
                    "type": "boolean"
                },
                "model_name": {
                    "type": "string"
                },
                "output_price_tokens": {
                    "type": "number"
                },
                "provider_id": {
                    "type": "string"
                },
                "service_type": {
                    "$ref": "#/definitions/provider.ServiceType"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "provider.ServiceType": {
            "type": "string",
            "enum": [
                "ollama",
                "exolabs",
                "llama_cpp",
                "vllm"
            ],
            "x-enum-varnames": [
                "ServiceTypeOllama",
                "ServiceTypeExolabs",
                "ServiceTypeLlamaCPP",
                "ServiceTypeVLLM"
            ]
        },
        "provider.UpdateAPIURLRequest": {
            "type": "object",
            "required": [
                "api_url"
            ],
            "properties": {
                "api_url": {
                    "type": "string"
                }
            }
        },
        "provider.UpdateAPIURLResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "provider.UpdateModelRequest": {
            "type": "object",
            "required": [
                "input_price_tokens",
                "model_name",
                "output_price_tokens",
                "service_type"
            ],
            "properties": {
                "input_price_tokens": {
                    "type": "number",
                    "minimum": 0
                },
                "model_name": {
                    "type": "string"
                },
                "output_price_tokens": {
                    "type": "number",
                    "minimum": 0
                },
                "service_type": {
                    "type": "string",
                    "enum": [
                        "ollama",
                        "exolabs",
                        "llama_cpp",
                        "vllm"
                    ]
                }
            }
        },
        "provider.UpdatePauseRequest": {
            "type": "object",
            "required": [
                "paused"
            ],
            "properties": {
                "paused": {
                    "type": "boolean"
                }
            }
        },
        "provider.UpdatePauseResponse": {
            "type": "object",
            "properties": {
                "paused": {
                    "type": "boolean"
                }
            }
        },
        "provider.ValidateHMACRequest": {
            "type": "object",
            "required": [
                "hmac"
            ],
            "properties": {
                "hmac": {
                    "type": "string"
                }
            }
        },
        "provider.ValidateHMACResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "request_data": {
                    "type": "object",
                    "additionalProperties": true
                },
                "transaction_id": {
                    "type": "string"
                },
                "valid": {
                    "type": "boolean"
                }
            }
        },
        "provider_comm.SendRequestRequest": {
            "type": "object",
            "required": [
                "hmac",
                "model_name",
                "provider_id",
                "request_data"
            ],
            "properties": {
                "hmac": {
                    "type": "string"
                },
                "model_name": {
                    "type": "string"
                },
                "provider_id": {
                    "type": "string"
                },
                "provider_url": {
                    "type": "string"
                },
                "request_data": {
                    "type": "object",
                    "additionalProperties": true
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "api.inferoute.com",
	BasePath:         "/",
	Schemes:          []string{"https", "http"},
	Title:            "Inferoute API",
	Description:      "API for Inferoute orchestration and providers",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
